In [ ]:
import  pandas as pd
df = pd.read_excel('/content/08_Electric Vehicle (1).xlsx')

In [ ]:
df

,Unnamed: 0,vehicle_identification_number,city,postal_code,model_year,make,model
0,0,JTMAB3FV3P,Seabeck,98380,2023,TOYOTA,RAV4 PRIME
1,1,1N4AZ1CP6J,Bremerton,98312,2018,NISSAN,LEAF
2,2,5YJ3E1EA4L,Seattle,98101,2020,TESLA,MODEL 3
3,3,1N4AZ0CP8E,Seattle,98125,2014,NISSAN,LEAF
4,4,5YJYGDEE5L,Lynnwood,98036,2020,TESLA,MODEL Y
...,...,...,...,...,...,...,...
197,197,5LMYJ8XY4M,Snohomish,98296,2021,LINCOLN,AVIATOR
198,198,1C4RJXN6XR,Pullman,99163,2024,JEEP,WRANGLER
199,199,KNDPYDDH8R,Poulsbo,98370,2024,KIA,SPORTAGE
200,200,3MW39FS08P,Ephrata,98823,2023,BMW,330E
201,201,1FAHP3R47C,Kingston,98346,2012,FORD,FOCUS

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     202 non-null    int64
 1   vehicle_identification_number  202 non-null    object
 2   city                           202 non-null    object
 3   postal_code                    202 non-null    int64
 4   model_year                     202 non-null    int64
 5   make                           202 non-null    object
 6   model                          202 non-null    object
dtypes: int64(3), object(4)
memory usage: 11.2+ KB

In [ ]:
df.isnull().sum()

Unnamed: 0                       0
vehicle_identification_number    0
city                             0
postal_code                      0
model_year                       0
make                             0
model                            0
dtype: int64

In [ ]:
df['city'] = df['city'].fillna(df['city'].mode()[0])

In [ ]:
df['model_year'] = df['model_year'].fillna(df['model_year'].median())

In [ ]:
df['make'] = df['make'].fillna(df['make'].mode()[0])

In [ ]:
df['model'] = df['model'].fillna(df['model'].mode()[0])

In [ ]:
df['vehicle_identification_number'] = df['vehicle_identification_number'].fillna('Unknown')

In [ ]:
df.isnull().sum()

Unnamed: 0                       0
vehicle_identification_number    0
city                             0
postal_code                      0
model_year                       0
make                             0
model                            0
dtype: int64

In [ ]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [ ]:
df.columns

Index(['unnamed:_0', 'vehicle_identification_number', 'city', 'postal_code',
       'model_year', 'make', 'model'],
      dtype='object')

In [ ]:
df['model'] = df['model'].astype(str)
df.loc[df['model'].str.strip().str.fullmatch(r'\d+'), 'model'] = 'Unknown'

In [ ]:
df.describe(include='all')

,unnamed:_0,vehicle_identification_number,city,postal_code,model_year,make,model
count,202.000000,202,202,202.000000,202.000000,202,202
unique,NaN,170,52,NaN,NaN,23,44
top,NaN,Unknown,Seattle,NaN,NaN,TESLA,MODEL 3
freq,NaN,4,25,NaN,NaN,79,45
mean,100.500000,NaN,NaN,98357.707921,2018.589109,NaN,NaN
std,58.456537,NaN,NaN,327.301037,3.275794,NaN,NaN
min,0.000000,NaN,NaN,98008.000000,2011.000000,NaN,NaN
25%,50.250000,NaN,NaN,98102.250000,2017.000000,NaN,NaN
50%,100.500000,NaN,NaN,98290.000000,2019.000000,NaN,NaN
75%,150.750000,NaN,NaN,98502.000000,2020.000000,NaN,NaN
max,201.000000,NaN,NaN,99324.000000,2025.000000,NaN,NaN

In [ ]:
df.to_excel('08_Electric Vehicle.xlsx')