In [ ]:
import  pandas as pd
df = pd.read_excel('/content/08_Electric Vehicle (4).xlsx')

In [ ]:
df

,Vehicle Identification Number,City,Postal Code,Model Year,Make,Model
0,JTMAB3FV3P,Seabeck,98380,2023.0,TOYOTA,RAV4 PRIME
1,1N4AZ1CP6J,Bremerton,98312,2018.0,NISSAN,LEAF
2,5YJ3E1EA4L,Seattle,98101,2020.0,TESLA,MODEL 3
3,1N4AZ0CP8E,Seattle,98125,2014.0,NISSAN,LEAF
4,5YJYGDEE5L,Lynnwood,98036,2020.0,TESLA,MODEL Y
...,...,...,...,...,...,...
197,5LMYJ8XY4M,Snohomish,98296,2021.0,LINCOLN,AVIATOR
198,1C4RJXN6XR,Pullman,99163,2024.0,JEEP,WRANGLER
199,KNDPYDDH8R,Poulsbo,98370,2024.0,KIA,SPORTAGE
200,3MW39FS08P,Ephrata,98823,2023.0,BMW,330E
201,1FAHP3R47C,Kingston,98346,2012.0,FORD,FOCUS

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 6 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Vehicle Identification Number  198 non-null    object
 1   City                           200 non-null    object
 2   Postal Code                    202 non-null    int64
 3   Model Year                     200 non-null    float64
 4   Make                           200 non-null    object
 5   Model                          201 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.6+ KB

In [ ]:
df.isnull().sum()

Vehicle Identification Number    4
City                             2
Postal Code                      0
Model Year                       2
Make                             2
Model                            1
dtype: int64

In [ ]:
df['City'] = df['City'].fillna(df['City'].mode()[0])

In [ ]:
df['Model Year'] = df['Model Year'].fillna(df['Model Year'].median())

In [ ]:
df['Make'] = df['Make'].fillna(df['Make'].mode()[0])

In [ ]:
df['Model'] = df['Model'].fillna(df['Model'].mode()[0])

In [ ]:
df['Vehicle Identification Number'] = df['Vehicle Identification Number'].fillna('Unknown')

In [ ]:
df.isnull().sum()

Vehicle Identification Number    0
City                             0
Postal Code                      0
Model Year                       0
Make                             0
Model                            0
dtype: int64

In [ ]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [ ]:
df.columns

Index(['vehicle_identification_number', 'city', 'postal_code', 'model_year',
       'make', 'model'],
      dtype='object')

In [ ]:
df['model'] = df['model'].astype(str)
df.loc[df['model'].str.strip().str.fullmatch(r'\d+'), 'model'] = 'Unknown'

In [ ]:
df.describe(include='all')

,vehicle_identification_number,city,postal_code,model_year,make,model
count,202,202,202.000000,202.000000,202,202
unique,170,52,NaN,NaN,23,44
top,Unknown,Seattle,NaN,NaN,TESLA,MODEL 3
freq,4,25,NaN,NaN,79,45
mean,NaN,NaN,98357.707921,2018.589109,NaN,NaN
std,NaN,NaN,327.301037,3.275794,NaN,NaN
min,NaN,NaN,98008.000000,2011.000000,NaN,NaN
25%,NaN,NaN,98102.250000,2017.000000,NaN,NaN
50%,NaN,NaN,98290.000000,2019.000000,NaN,NaN
75%,NaN,NaN,98502.000000,2020.000000,NaN,NaN
max,NaN,NaN,99324.000000,2025.000000,NaN,NaN

In [ ]:
df.to_excel('08_Electric Vehicle.xlsx')